	SUBROUTINE tide_heat (DPGQSP, TIM)

C...READS HEATING TEMPORAL FFT OF SPHERICAL HARMONIC COEFFICIENTS
C...RECONSTRUCTS ON THE TIME GRID, AND INTERPOLATES TO THE MODEL ALTITUDE GRID
c...same as tide/code/spectrum_heat.f
c..input files written by f:/waccm/make_heat_file

	IMPLICIT NONE

	INCLUDE 'mcons.inc'
	INCLUDE 'spcons.inc'
	INCLUDE 'mgrid.inc'
	INCLUDE 'spgrid.inc'

	REAL TIM
	COMPLEX DPGQSP(0:M1MAX,0:N1MAX,NPGQ,L1MAX)

	INTEGER IER, WLUN

	INTEGER I, J, K, L, M, N
	LOGICAL FIRST /.TRUE./

	INTEGER MAXZW,MAXLEG,MAXLEV,MAXFRQ
	PARAMETER(MAXZW=10, MAXLEG=40, MAXLEV=160,MAXFRQ=20)

	COMPLEX EXPT, IC2PI /(0.,6.28319)/
	REAL COEFR(0:MAXZW,0:MAXLEG,MAXLEV,MAXFRQ)
	REAL COEFI(0:MAXZW,0:MAXLEG,MAXLEV,MAXFRQ)
	REAL ZG(MAXLEV), Z(L1MAX)! heating and model altitude grids
	COMPLEX CO1, CO2
	REAL WT1, WT2, WT(L1MAX)
	INTEGER LMN, LMX, INDX(L1MAX), LX1, LX2

        CHARACTER*80 ARG
	INTEGER IARG
	COMMON /OPENS/ IARG

	real ramp

	INTEGER NZON		!# ZONAL WAVENUMBERS
	INTEGER NLEG		!# LEGENDRE POLYNOMIALS (0-NLEG)
	INTEGER NALT		!# ALTITUDES IN HEATING GRID
	INTEGER NFREQ		!# FFT FREQUENCIES
	REAL CPS		!FFT FREQUENCY INTERVAL, CYCLES PER SECOND
	real time0

C     Input and output folders and files
      CHARACTER*50 INFOLD, INFILE, OUTFOLD, OUTFILE, TIDEFILE, TTIDEFILE
      CHARACTER*50 INITTEMP, INITZONAL, INITGRID, INITZGRID, GWFDUMP, CURT
      CHARACTER*50 SURFFILE
      COMMON /FILES/ INFOLD, INFILE, SURFFILE, OUTFOLD, OUTFILE,
     1   INITTEMP, INITZONAL, INITGRID, GWFDUMP, TIDEFILE, TTIDEFILE,CURT
C------------------------------------------------------------------

	IF (FIRST) THEN
	  WLUN=277
	  CALL GETARG(IARG,ARG)	!CONTINUE RUN FROM THIS FILE
	  OPEN(WLUN, FILE=ARG(1:(INDEX(ARG,' ')-1)), STATUS='OLD',SHARED)
	  IARG=IARG+1

	  FIRST=.FALSE.

	  READ(WLUN,*) NZON, NFREQ, NLEG, NALT, CPS

	  IF ((NZON .GT. MAXZW) .OR.(NFREQ .GT. MAXFRQ) .OR. (NLEG .GT. MAXLEG)
	1      .OR. (NALT .GT. MAXLEV)) THEN
	    WRITE(6,*) 'HEATING INPUT PARAMETERS TOO LARGE'
	    STOP
	  ENDIF

	  READ (WLUN,*) (ZG(I),I=1,NALT)
	  READ (WLUN,*) ((((COEFR(I,J,L,N),I=0,NZON),J=0,NLEG),L=1,NALT),N=1,NFREQ)
	  READ (WLUN,*) ((((COEFI(I,J,L,N),I=0,NZON),J=0,NLEG),L=1,NALT),N=1,NFREQ)

	  IC2PI = IC2PI*CPS

	  DO L=1,L1
	    Z(L)=-7.*ALOG(PLV(L1-L+1)*PSURF/1.E5)
	  ENDDO

C...SET UP ALTITUDE RANGE OF HEATING AND INTERPOLATION COEFFICIENTS
	  LMX=0
	  DO L=1,L1
	    IF (Z(L) .LT. ZG(NALT)) LMX=L
	  ENDDO

	  LMN=L1
	  DO L=L1,1,-1
	    IF (Z(L) .GT. ZG(1)) LMN=L
	  ENDDO

	  DO I=LMN,LMX
	    INDX(I)=1
	    DO J=1,NALT-1
	      IF (ZG(J) .LT. Z(I)) INDX(I)=J
	    ENDDO
	  ENDDO

	  DO K=LMN,LMX
	    WT(K)=(Z(K)-ZG(INDX(K))) / (ZG(INDX(K)+1)-ZG(INDX(K)))
	  ENDDO

	  time0=tim
	ENDIF

	RAMP=.5*(1+TANH(((TIM-time0)/86400.-2)/2.))

	DO I=1,NFREQ
	  IF (I .LE.  NFREQ/2 + 1) THEN
	    EXPT=EXP(IC2PI*(I-1)*TIM)*RAMP
	  ELSE
	    EXPT=EXP(IC2PI*(I-NFREQ-1)*TIM)*RAMP
	  ENDIF

	  DO L=LMN,LMX
	    K=L1+1-L
	    LX1=INDX(L)
	    LX2=LX1+1
	    WT2=WT(L)
	    WT1=(1.-WT2)

	    DO N=0,N1
	      DO M=0,MIN0(N,NZON)
		CO1=CMPLX(COEFR(M,N,LX1,I),COEFI(M,N,LX1,I))
		CO2=CMPLX(COEFR(M,N,LX2,I),COEFI(M,N,LX2,I))

		DPGQSP(M,N,JPOT,K) = DPGQSP(M,N,JPOT,K) + (WT1*CO1+WT2*CO2)*EXPT
	      END DO
	    END DO

	  END DO
	END DO

	END
