#=============================================================================
FOBJ ?=	\
	prism_Driver.o Timing_mod.o coolmd_mod.o Declarations_mod.o \
	Prognos_sigma_mod.o splib2_mod.o linpack_mod.o

# default target
all:
