#=============================================================================
FOBJ ?=	\
	prism_Driver.o Timing_mod.o coolmd_mod.o Declarations_mod.o \
	Prognos_sigma_mod.o splib2_mod.o linpack_mod.o IO_mod.o Config_mod.o \
    heating_mod.o 2d_interp.o r8_lib.o forcing_mod.o

# default target
all:
